# Generated by Django 5.2.8 on 2025-11-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(max_length=100)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('codigo_interno', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_ips', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_ecri', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('clasificacion_misional', models.CharField(blank=True, max_length=50, null=True)),
                ('clasificacion_ips', models.CharField(blank=True, max_length=50, null=True)),
                ('clasificacion_riesgo', models.CharField(blank=True, max_length=50, null=True)),
                ('registro_invima', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo_vida_util', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('propietario', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_fabricacion', models.CharField(blank=True, max_length=50, null=True)),
                ('nit', models.CharField(blank=True, max_length=50, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('en_garantia', models.BooleanField(default=False)),
                ('fecha_fin_garantia', models.DateField(blank=True, null=True)),
                ('forma_adquisicion', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('hoja_vida', models.BooleanField(default=False)),
                ('registro_importacion', models.BooleanField(default=False)),
                ('manual_operacion', models.BooleanField(default=False)),
                ('manual_mantenimiento', models.TextField(blank=True, null=True)),
                ('guia_rapida', models.BooleanField(default=False)),
                ('instructivo', models.BooleanField(default=False)),
                ('protocolo_mto', models.TextField(blank=True, null=True)),
                ('frecuencia_metrologica', models.CharField(blank=True, max_length=50, null=True)),
                ('mantenimiento', models.BooleanField(default=False)),
                ('frecuencia_mantenimiento', models.IntegerField(blank=True, null=True)),
                ('calibracion', models.BooleanField(default=False)),
                ('frecuencia_calibracion', models.IntegerField(blank=True, null=True)),
                ('magnitud', models.CharField(blank=True, max_length=50, null=True)),
                ('rango', models.CharField(blank=True, max_length=100, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=50, null=True)),
                ('rango_trabajo', models.CharField(blank=True, max_length=50, null=True)),
                ('error_maximo', models.CharField(blank=True, max_length=50, null=True)),
                ('voltaje', models.CharField(blank=True, max_length=50, null=True)),
                ('corriente', models.CharField(blank=True, max_length=50, null=True)),
                ('humedad', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=50, null=True)),
                ('dimensiones', models.CharField(blank=True, max_length=100, null=True)),
                ('peso', models.CharField(blank=True, max_length=50, null=True)),
                ('otros', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
