# Generated by Django 5.2.8 on 2025-11-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_edicionequipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicionequipo',
            name='responsable_actualizado',
            field=models.CharField(blank=True, default='Sin responsable asignado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='edicionequipo',
            name='servicio_actualizado',
            field=models.CharField(default='Sin servicio asignado', max_length=100),
        ),
    ]
