# Generated by Django 5.2.8 on 2025-11-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_edicionequipo_responsable_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicionequipo',
            name='responsable_actualizado',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='edicionequipo',
            name='servicio_actualizado',
            field=models.TextField(max_length=100),
        ),
    ]
