# Generated by Django 4.2 on 2025-11-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_edicionequipo_responsable_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='clasificacion_ips',
            field=models.CharField(blank=True, choices=[('BIO', 'BIO'), ('IND', 'IND'), ('GASES', 'Gases')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='clasificacion_misional',
            field=models.CharField(blank=True, choices=[('DOCENCIA', 'Docencia'), ('INVESTIGACION', 'Investigación'), ('EXTENSION', 'Extensión')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='clasificacion_riesgo',
            field=models.CharField(blank=True, choices=[('I', 'Clase I'), ('IIA', 'Clase IIa'), ('IIB', 'Clase IIb'), ('III', 'Clase III')], max_length=50, null=True),
        ),
    ]
