# Generated by Django 4.2 on 2025-11-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_equipo_clasificacion_ips_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='dimensiones',
        ),
        migrations.AddField(
            model_name='equipo',
            name='dimensiones_alto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='dimensiones_ancho',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='dimensiones_profundidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='sede',
            field=models.CharField(blank=True, choices=[('PRADO', 'Sede Prado'), ('SEDE2', 'Sede 2'), ('SEDE3', 'Sede 3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='frecuencia_metrologica',
            field=models.BooleanField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='manual_mantenimiento',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='protocolo_mto',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
