# Generated by Django 4.2 on 2025-11-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_equipo_dimensiones_equipo_dimensiones_alto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='dimensiones_alto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='dimensiones_ancho',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='dimensiones_profundidad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
