# Generated by Django 4.2 on 2025-11-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_equipo_dimensiones_alto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='sede',
            field=models.CharField(blank=True, choices=[('Sede Prado', 'Sede Prado'), ('Sede Prado', 'Sede 2'), ('Sede Prado', 'Sede 3')], max_length=50, null=True),
        ),
    ]
