# Generated by Django 4.2 on 2025-11-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_equipo_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='sede',
            field=models.CharField(blank=True, choices=[('Prado', 'Prado'), ('SIU', 'SIU'), ('San Vicente', 'San Vicente')], max_length=50, null=True),
        ),
    ]
