# Generated by Django 5.2.8 on 2025-11-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_equipo_activo_alter_equipo_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fecha_adquisicion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_fin_garantia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
