# Generated by Django 5.2.8 on 2025-11-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_equipo_fecha_adquisicion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='dimensiones_alto',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='dimensiones_ancho',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='dimensiones_profundidad',
        ),
        migrations.AddField(
            model_name='equipo',
            name='dimensiones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
