# Generated by Django 5.2.8 on 2025-11-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_equipo_dimensiones_alto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='clasificacion_misional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
