# Generated by Django 5.2.8 on 2025-11-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_equipo_clasificacion_misional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='clasificacion_misional',
            field=models.CharField(blank=True, choices=[('Docencia', 'Docencia'), ('Investigación', 'Investigación'), ('Extensión', 'Extensión')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='clasificacion_riesgo',
            field=models.CharField(blank=True, choices=[('I', 'Clase I'), ('IIa', 'Clase IIa'), ('IIb', 'Clase IIb'), ('III', 'Clase III')], max_length=50, null=True),
        ),
    ]
