# Generated by Django 5.2.8 on 2025-11-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_equipo_clasificacion_misional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='valor_compra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
