# Generated by Django 5.2.8 on 2025-11-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_equipo_valor_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='clasificacion_ips',
            field=models.CharField(blank=True, choices=[('BIO', 'BIO'), ('IND', 'IND'), ('GASES', 'Gases')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='clasificacion_misional',
            field=models.CharField(blank=True, choices=[('Docencia', 'Docencia'), ('Investigación', 'Investigación'), ('Extensión', 'Extensión')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='clasificacion_riesgo',
            field=models.CharField(blank=True, choices=[('I', 'Clase I'), ('IIa', 'Clase IIa'), ('IIb', 'Clase IIb'), ('III', 'Clase III')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='codigo_ecri',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='codigo_ips',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='corriente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='error_maximo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_adquisicion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_fabricacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_fin_garantia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='forma_adquisicion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='frecuencia_calibracion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='frecuencia_mantenimiento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='frecuencia_metrologica',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='guia_rapida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='humedad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='instructivo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='magnitud',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='manual_mantenimiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='manual_operacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre_equipo',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='peso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='propietario',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='protocolo_mto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='proveedor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='rango',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='rango_trabajo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='registro_importacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='registro_invima',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='resolucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='responsable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='sede',
            field=models.CharField(blank=True, choices=[('Prado', 'Prado'), ('SIU', 'SIU'), ('San Vicente', 'San Vicente')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tiempo_vida_util',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo_documento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='valor_compra',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='voltaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
