# Generated by Django 5.2.8 on 2025-11-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_equipo_clasificacion_ips_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='calibracion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='clasificacion_riesgo',
            field=models.CharField(blank=True, choices=[('I', 'Clase I'), ('IIA', 'Clase IIa'), ('IIB', 'Clase IIb'), ('III', 'Clase III')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='en_garantia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='hoja_vida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='mantenimiento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
