# Generated by Django 5.2.8 on 2025-11-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_equipo_calibracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edicionequipo',
            name='responsable_actualizado',
        ),
        migrations.RemoveField(
            model_name='edicionequipo',
            name='servicio_actualizado',
        ),
        migrations.AddField(
            model_name='edicionequipo',
            name='responsable_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='edicionequipo',
            name='responsable_nuevo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='edicionequipo',
            name='sede_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='edicionequipo',
            name='sede_nueva',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='edicionequipo',
            name='servicio_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='edicionequipo',
            name='servicio_nuevo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='edicionequipo',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
