# Generated by Django 5.2.8 on 2025-11-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_edicionequipo_responsable_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicionequipo',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
