# Generated by Django 5.2.8 on 2025-11-30 13:56

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_edicionequipo_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreusuario', models.CharField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('viewer', 'Solo lectura')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='equipo',
            name='clasificacion_misional',
            field=models.TextField(blank=True, null=True, validators=[api.models.validar_clasificacion_misional]),
        ),
        migrations.CreateModel(
            name='DesactivacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desactivacion', models.DateField(auto_now_add=True)),
                ('responsable_desactivacion', models.CharField(max_length=100)),
                ('justificacion', models.TextField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipo')),
            ],
        ),
    ]
