# Generated by Django 5.2.8 on 2025-11-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_usuario_alter_equipo_clasificacion_misional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
